import { createRoot } from "react-dom/client";
import "@fontsource/dm-sans/400.css";
import "@fontsource/dm-sans/500.css";
import "@fontsource/dm-sans/600.css";
import "@fontsource/dm-sans/700.css";
import "@fontsource/fraunces/400.css";
import "@fontsource/fraunces/500.css";
import { App } from "./app/App";
import "./styles/global.css";
import "./styles/readability.css";
import "./styles/journey-additions.css";
createRoot(document.getElementById("root")!).render(<App />);
